name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  extension:
    name: Pack MailExtension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip
        run: |
          pushd ./extension
          zip -r -FS ../external-editor-revived.xpi *
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: thunderbird-extension
          retention-days: 60
          path: |
            external-editor-revived.xpi

  messaging_host:
    name: Build, lint, and test messaging host
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        rust_toolchain: [stable]
        experimental: [false]
        include:
          - os: ubuntu-latest
            rust_toolchain: nightly
            experimental: true
          - os: macos-latest
            rust_toolchain: nightly
            experimental: true
          - os: windows-latest
            rust_toolchain: nightly
            experimental: true

    steps:
      - uses: actions/checkout@v2
      - name: Git Commit Hash
        id: git_commit
        run: |
          echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: Cancel Previous Runs
        if: contains(matrix.os, 'ubuntu')
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}

      - name: Install Rust Toolchain
        id: rust_toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust_toolchain }}
          default: true
          override: true
          components: rustfmt, clippy
      - name: Add macOS Targets
        if: contains(matrix.os, 'macos')
        run: |
          rustup target add x86_64-apple-darwin
          rustup target add aarch64-apple-darwin

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: build-${{ runner.os }}-rustc-${{ steps.rust_toolchain.outputs.rustc_hash }}-lock-${{ hashFiles('Cargo.lock') }}-git-${{ steps.git_commit.outputs.hash }}
          restore-keys: |
            build-${{ runner.os }}-rustc-${{ steps.rust_toolchain.outputs.rustc_hash }}-lock-${{ hashFiles('Cargo.lock') }}-
            build-${{ runner.os }}-rustc-${{ steps.rust_toolchain.outputs.rustc_hash }}-
            build-${{ runner.os }}-

      - name: rustfmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked --tests -- -D warnings

      - name: Build (Linux, Windows)
        if: "!contains(matrix.os, 'macos')"
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release
      - name: Build (macOS, x86_64)
        if: contains(matrix.os, 'macos')
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release --target=x86_64-apple-darwin
      - name: Build (macOS, aarch64)
        if: contains(matrix.os, 'macos')
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked --release --target=aarch64-apple-darwin
      - name: macOS Universal Binary
        if: contains(matrix.os, 'macos')
        run: |
          mkdir -p target/release/
          lipo -create -output target/release/external-editor-revived target/x86_64-apple-darwin/release/external-editor-revived target/aarch64-apple-darwin/release/external-editor-revived
          file target/release/external-editor-revived
      - name: Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-${{ matrix.rust_toolchain }}-native-messaging-host
          retention-days: 60
          path: |
            target/release/external-editor-revived
            target/release/external-editor-revived.exe

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --locked --release
